### ISSUE TITLE
QPSMPGP has too verbose output

### ISSUE THREAD

**Issue by haplav** [It4innovations/permon#36]
It monitors convergence although it's not asked to do so - prints lines like
```
180 MPGP [c] ||gp||=9.9891341100e-09,	||phi||=9.9891341100e-09,	||beta||=0.0000000000e+00,	alpha=1.2017124429e-01
```

**Comment by jkruzik** [comment]
What code is that in and what is the output with `-options_view`?
This should be printed only when you pass `-qps_monitor true` or set the default monitor by `QPSMonitorSet(qps,QPSMonitorDefault,NULL,0)`

**Comment by haplav** [comment]
* https://github.com/permon/permon/blob/master/src/tutorials/jbearing2.c#L576
* https://github.com/permon/permon/blob/master/src/tutorials/output/jbearing2_4.out

There is no `-qps_monitor true`. That's my point.

**Comment by jkruzik** [comment]
That is due to an explicit QPSMonitorSet in https://github.com/permon/permon/blob/19a72fa7788c304cbbeadd45c6be8954152ef547/src/tutorials/jbearing2.c#L531

You should be able to cancel it with -qps_monitor_cancel but even though it is in the docs, it is missing in QPSSetFromOptions().

I would keep it the jbearing2 tutorial (it is an example how to use QPSMonitorSet, and provides us with a warning if MPRGP takes a different step).

**Comment by haplav** [comment]
OK, I haven't anticipated nor noticed there's implicit QPSMonitorSet(). Fair enough.

> You should be able to cancel it with -qps_monitor_cancel but even though it is in the docs, it is missing in QPSSetFromOptions().

OK, this is an issue but separate from this one.

**Comment by haplav** [comment]
So this is not relevant, closing.
